# Licensed under the Apache-2.0 license

[package]
name = "lwip-rs-example"
version = "0.1.0"
edition = "2021"
description = "DHCP + TFTP boot example application using lwip-rs"

[[bin]]
name = "lwip-rs-example"
path = "src/main.rs"

[dependencies]
lwip-rs.workspace = true
