# Licensed under the Apache-2.0 license

[package]
name = "mcu-config-fpga"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
mcu-config.workspace = true

[features]
default = []
extended_axi_user = []